server:
  port: 8088
spring:
  application:
    name: test‐freemarker
  freemarker:
    cache: false # 模板缓存，测试的时候可以先关闭。
    settings:
      template_update_delay: 0 # 检查模板更新延迟时间，设置为0表示立即检查。
                               # 如果时间大于0会有缓存不方便,进行模板测试。


      #FreeMarker是会缓存模板的。当调用getTemplate方法时，
      #FreeMarker不但返回了Template对象的结果，而且还会将它存储在缓存中，
      #当下一次再以相同路径调用getTemplate方法时，
      #那么它只返回缓存的Tempalte实例，而不会再次加载和解析模板文件。

      #如果更改了模板文件，当下次调用模板时，FreeMarker会自动重新载入和解析模板。
      #要检查模板文件是否改变内容了是需要时间的，
      #有一个Configuration级别的设置被称作“更新延迟”可以用来设置这个时间，
      #默认是5秒。如果想要看到模板立即更新的效果，那么就要把它设置为0.


    template-loader-path: classpath:mytemplates/ # 设置模板的位置,默认classpath的templates下。
    suffix: .ftl #默认后缀为.ftl 视图跳转时可以省略
